### PR TITLE
Some updates

### PR DESCRIPTION
**Pull request by caternuson**
* add headers guards for issue #41 and #33
* changes examples to .ino
* update version/desc in libraries.property

### CODE REVIEW

**Comment by caternuson** [comment]
Travis is failing due to lack of gh-pages branch.

**Comment by ladyada** [comment]
do you want to actionify?

**Comment by caternuson** [comment]
I think it's mostly done - just not sure of the "correct" way to create initial `gh-pages` branch. Know how to do it for forked copy. But don't think it can be added back via PR. Could just push directly to this repo, but hesitant to do that.

**Comment by ladyada** [comment]
np i did it

**Comment by caternuson** [comment]
cool. thanks. just restarted the job on the last commit and it's all happy now.

**Pull request merged**
