### PR TITLE
Pull request consolidation and other enhancements

### PR DESCRIPTION
**Pull request by soligen2010**
Modified by soligen2010 - consolidation of pull requests and other stuff
Moved conversion delay out of getLastConversionResults into
startComparator_SingleEnded so the method can be used more generically.
Re-factored out duplicated code in differential reads
Re-factored out duplicated code for single ended MUX bit settings
Added support for differential reads between pins 0,3 and 1,3 (was also
done by ycheneval in pull request #6)
Added voltsPerBit() as a convenience
Added keywords.txt (Pull request #8 from dhhagen)
Fix for single ended int overflow (Pull request #9 from jamesfowkes)
Added include guard (Pull request #11 from Ivan-Perez)
Added begin method for ESP8266 systems (from Pontus Oldberg)
Ability to configure Samples per Second and set corresponding Conversion
Delay (Adapted from romainreignier)
In startComparator_SingleEnded explicitly set the low threshold to the
default.
Added methods that return actual voltage as a float.
Renamed constants that were common to both chips to ADS1X15....

### CODE REVIEW

**Comment by palomarcoder** [comment]
I'm pretty new to github - I see this looks like a good set of contributions / fixes - does anyone from Adafruit actually merge these pull requests?

**Comment by soligen2010** [comment]
It appears no. That is why I did a fork of this library.

**Comment by chinswain** [comment]
@ladyada Could you merge this?

**Comment by ladyada** [comment]
hiya this requires testing because a *lot* has changed but will add to our list

please remove the library.json file - we don't support maintaining it!

**Comment by soligen2010** [comment]
I removed library.json

**Comment by soligen2010** [comment]
I also made changes listed at #32

**Comment by SRGDamia1** [comment]
Is there any chance this PR will be accepted?

**Comment by andrei128x** [comment]
@soligen2010 could you solve the merge conflicts, please ?

**Review by andrei128x — APPROVED** [review]

**Comment by caternuson** [comment]
@soligen2010 Very sorry this never got merged. It just sort of fell through the cracks. There was good work here.

**Pull request closed without merging**
